dist: bionic
language: python

matrix:
  include:
    - python: 3.8
      env: TOXENV=py38
    - python: 3.6
      env: TOXENV=py36

script:
  - tox

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - henne64@googlemail.com
    - daniel.henneberg@aufbaubank.de
