dist: bionic
language: python
matrix:
  include:
  - python: 3.8
    env: TOXENV=py38
  - python: 3.6
    env: TOXENV=py36
script:
- tox
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  user: __token__
  password:
    secure: YW0ckst2KxrHWeVdZCQhQD6zdxiEXpCP/43OzhENdrH6VIs0sCo1aNKgR1I8CLg1bnmEWpHcrTElJwivLxO5VtjWde5rUouz5SImHm8GT+BEdk62VqhU7C0Dfr70UAsQ9fZTeDwXV15R25oLzD8+zQcaQrOM/0UjkJiGRfbV8XALJZ98T04pw8XysITj3P4EcPiY72BZMuG0pNHeWM0+u/PMttYtFjLNoMIqkXvFerrPOppg1yDnfS5leorDtsB+2FL2xXF7IP617+Iw2vYqov9Mt3LewV1EQH9A6Lgx/suZviNs1vojsFUgEZSaOCh1nkGE0SuzO2T+VOYRLvAUBeJQemVsXZXB09cAp3MRGBDnxo0wRk0XUa3p6amS2hL23HRKCd8Qk9JSRkFF+0AbyVe/PvRJr2wt/eVRNOxIcuXYIpv3TYc+rp8N8whUzbwZ45FnWeVCTxW/xSsdieDpcxW0xiAQ7dgfbjBLQlBVnn0V9nPPjnoknsY0/9Y8fllwqMdXHfIaxTBdWstdQn7be4W2Q1jx5eejJjp5YWMNInoHNr1yNA2B/bonSZCDoxplXZtPvRz8Xh6EI0IlvcrYlfwBoeLoyv0g5xyGWTqCtGCIScgtaN1ddurV6U76+Jo/1tI0EN7v/LnvCsBtiq1K+jCN3JcrhmqQJWHf/oq/MAA=
  distributions: sdist bdist_wheel
  skip_existing: true
notifications:
  email:
  - henne64@googlemail.com
  - daniel.henneberg@aufbaubank.de
